-- Phase 2 + Phase 3 content models migration. Generated to match the current
-- prisma/schema.prisma. Apply after the Phase 0/1 init migration.
-- NOTE: This is a representative migration for review — run `prisma migrate dev`
-- against a real database to generate the authoritative, exactly-matching SQL.

-- Enums
CREATE TYPE "MediaType" AS ENUM ('IMAGE', 'VIDEO', 'PDF', 'DOCUMENT', 'SVG');
CREATE TYPE "NavigationContext" AS ENUM ('HEADER', 'FOOTER');
CREATE TYPE "LinkType" AS ENUM ('INTERNAL', 'EXTERNAL');
CREATE TYPE "PostStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'SCHEDULED');

-- This migration file is a structural placeholder documenting the intended
-- change set. Given this environment has no database connection, the
-- authoritative migration must be generated by running:
--   npx prisma migrate dev --name phase2_phase3_content
-- against a real Neon database, which will introspect schema.prisma directly
-- and emit exact, guaranteed-correct SQL (including all Phase 2/3 tables:
-- MediaFolder, Media, Setting, ThemeConfig, NavigationMenu, NavigationItem,
-- FooterConfig, ServiceCategory, Service, ServiceFeature, ServiceBenefit,
-- ServiceProcessStep, ServiceFaq, Industry, IndustryChallenge,
-- IndustrySolutionMapping, IndustryFaq, ProjectCategory, Technology, Project,
-- ProjectTechnology, ServiceTechnology, ProjectNarrative, ProjectMetric,
-- ProjectMedia, TeamMember, TeamMemberSkill, SocialLink, Testimonial,
-- PostCategory, Tag, Post, PostTag, PostRelated, GlobalFaq, SeoOverride,
-- GlobalSeoConfig).
--
-- Hand-writing 40+ CREATE TABLE statements here risks a transcription error
-- that `prisma migrate dev` cannot make — it generates directly from the
-- schema AST. Documenting this honestly rather than producing SQL I cannot
-- verify against the schema is the correct trade-off for a migration file
-- (unlike the Phase 0/1 migration, which was small enough to hand-verify
-- line-by-line against the schema and cross-checked programmatically).

-- AUDIT UPDATE (post Phase 0-3 audit): the following relation fixes were made
-- to schema.prisma after this migration file was first drafted and must be
-- included when running `prisma migrate dev`:
--   - Project.testimonialId / nextProjectId converted from orphaned scalar
--     FKs into real relations (Project -> Testimonial, and a self-relation
--     "ProjectNext" for the next-project pointer).
--   - IndustrySolutionMapping.serviceId given a real relation to Service
--     (previously only related to Industry; the mapped Service could never
--     actually be queried).
--   - ServiceTechnology.serviceId given a real relation to Service
--     (previously only related to Technology).
--   - ProjectMedia.mediaId given a real relation to Media (previously a bare
--     string; cover images could never be resolved to an actual URL).
-- These are exactly the kind of change `prisma migrate dev` is designed to
-- pick up automatically from the current schema.prisma — no manual SQL
-- reconciliation needed if you run it fresh against this schema version.
